apiVersion: apps/v1
kind: Deployment
metadata:
  name: ub-frontend
  labels:
    app: ub-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app : ub-frontend
  template:
    metadata:
      labels:
        app: ub-frontend
    spec:
      containers:
      - name: ub-frontend
        image: dbovenzi/ubiquitousbyte:1.4
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi" #256 MB
            cpu: "200m" #200 millicpu (.2 cpu or 20% of the cpu)
      imagePullSecrets:
      - name: regcred