apiVersion: v1
kind: Service
metadata:
  name: ub-service 
  labels:
    app: ub-frontend
    app.kubernetes.io/name: ub-frontend
    app.kubernetes.io/component: website
    app.kubernetes.io/part-of: ubiquitousbyte-system
    app.kubernetes.io/managed-by: helm
spec:
  type: NodePort
  selector:
    app: ub-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000