name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile.ubuntu-arm64 --tag dbovenzi/ubiquitousbyte:pi-latest
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dbovenzi/ubiquitousbyte:1.3
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile.ubuntu-arm64
  deploy:
    needs: build
    runs-on: [self-hosted, k8s]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to cluster
        run: microk8s.kubectl apply -f deploy/k8s-deployment.yaml